name: Python CI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html 
          pip install -r requirements.txt 
      - name: Run tests
        run: |
          pytest --html=report.html /rasa_hometest_ashok/task_cli_tests.py 

