name: Python CI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          node-version: '20'
          
      - name: Install taskwarrior
        run: |
          sudo apt-get update
          sudo apt-get install taskwarrior -y
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify Python version
          node-version: '20'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html 
      - name: Run TASK-CLI-Tests
        run: |
          pytest --html=rasa_hometest_ashok/report.html rasa_hometest_ashok/task_cli_tests.py 
        env:
          PYTHONPATH: ./
        

