name: Taskwarrior and API  CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  RASA-HOMETEST-CIJOB:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          node-version: '20'
          
      - name: Install taskwarrior
        run: |
          sudo apt-get update
          sudo apt-get install taskwarrior -y
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify Python version
          node-version: '20'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html 
          pip install requests pytest
      - name: Run RASA-TASK-CLI Tests
        run: |
          pytest --html=rasa_hometest_ashok/task_cli_test/taskclitest.html rasa_hometest_ashok/task_cli_test/task_cli_tests.py 
      - name: Run RASA-FAKESTORE-API Tests2
        run: |
          pytest --html=rasa_hometest_ashok/fakestoreapitests/fakestoreapitest.html rasa_hometest_ashok/fakestoreapitests/fakestorapitest.py
        env:
          PYTHONPATH: ./
        

